// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module farthest_point_sampling_pow_generic_double_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        base_r,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [63:0] base_r;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
reg    ap_block_pp0_stage0_11001;
wire   [5:0] pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_V_address0;
reg    pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_V_ce0;
wire   [5:0] pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_V_q0;
wire   [5:0] pow_reduce_anonymous_namespace_log0_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_double_0_5_64_array_V_address0;
reg    pow_reduce_anonymous_namespace_log0_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_double_0_5_64_array_V_ce0;
wire   [108:0] pow_reduce_anonymous_namespace_log0_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_double_0_5_64_array_V_q0;
wire   [3:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_4_4_16_array_V_address0;
reg    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_4_4_16_array_V_ce0;
wire   [104:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_4_4_16_array_V_q0;
wire   [5:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_7_6_64_array_V_address0;
reg    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_7_6_64_array_V_ce0;
wire   [101:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_7_6_64_array_V_q0;
wire   [5:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_12_6_64_array_V_address0;
reg    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_12_6_64_array_V_ce0;
wire   [96:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_12_6_64_array_V_q0;
wire   [5:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_17_6_64_array_V_address0;
reg    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_17_6_64_array_V_ce0;
wire   [91:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_17_6_64_array_V_q0;
wire   [5:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_22_6_64_array_V_address0;
reg    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_22_6_64_array_V_ce0;
wire   [86:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_22_6_64_array_V_q0;
wire   [5:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_27_6_64_array_V_address0;
reg    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_27_6_64_array_V_ce0;
wire   [81:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_27_6_64_array_V_q0;
wire   [5:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_32_6_64_array_V_address0;
reg    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_32_6_64_array_V_ce0;
wire   [76:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_32_6_64_array_V_q0;
wire   [7:0] pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0;
reg    pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0;
wire   [57:0] pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0;
wire   [7:0] pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0;
reg    pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0;
wire   [25:0] pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0;
wire   [7:0] pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address1;
reg    pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce1;
wire   [25:0] pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q1;
wire   [7:0] pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0;
reg    pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0;
wire   [41:0] pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0;
wire   [51:0] p_Repl2_s_fu_586_p1;
reg   [51:0] p_Repl2_s_reg_2257;
wire   [0:0] icmp_ln828_fu_606_p2;
reg   [0:0] icmp_ln828_reg_2263;
reg   [0:0] icmp_ln828_reg_2263_pp0_iter1_reg;
reg   [0:0] icmp_ln828_reg_2263_pp0_iter2_reg;
reg   [0:0] icmp_ln828_reg_2263_pp0_iter3_reg;
reg   [0:0] icmp_ln828_reg_2263_pp0_iter4_reg;
reg   [0:0] icmp_ln828_reg_2263_pp0_iter5_reg;
reg   [0:0] icmp_ln828_reg_2263_pp0_iter6_reg;
reg   [0:0] icmp_ln828_reg_2263_pp0_iter7_reg;
reg   [0:0] icmp_ln828_reg_2263_pp0_iter8_reg;
reg   [0:0] icmp_ln828_reg_2263_pp0_iter9_reg;
reg   [0:0] icmp_ln828_reg_2263_pp0_iter10_reg;
reg   [0:0] icmp_ln828_reg_2263_pp0_iter11_reg;
reg   [0:0] icmp_ln828_reg_2263_pp0_iter12_reg;
reg   [0:0] icmp_ln828_reg_2263_pp0_iter13_reg;
reg   [0:0] icmp_ln828_reg_2263_pp0_iter14_reg;
reg   [0:0] icmp_ln828_reg_2263_pp0_iter15_reg;
reg   [0:0] icmp_ln828_reg_2263_pp0_iter16_reg;
wire   [0:0] x_is_1_fu_612_p2;
reg   [0:0] x_is_1_reg_2268;
reg   [0:0] x_is_1_reg_2268_pp0_iter1_reg;
reg   [0:0] x_is_1_reg_2268_pp0_iter2_reg;
reg   [0:0] x_is_1_reg_2268_pp0_iter3_reg;
reg   [0:0] x_is_1_reg_2268_pp0_iter4_reg;
reg   [0:0] x_is_1_reg_2268_pp0_iter5_reg;
reg   [0:0] x_is_1_reg_2268_pp0_iter6_reg;
reg   [0:0] x_is_1_reg_2268_pp0_iter7_reg;
reg   [0:0] x_is_1_reg_2268_pp0_iter8_reg;
reg   [0:0] x_is_1_reg_2268_pp0_iter9_reg;
reg   [0:0] x_is_1_reg_2268_pp0_iter10_reg;
reg   [0:0] x_is_1_reg_2268_pp0_iter11_reg;
reg   [0:0] x_is_1_reg_2268_pp0_iter12_reg;
reg   [0:0] x_is_1_reg_2268_pp0_iter13_reg;
reg   [0:0] x_is_1_reg_2268_pp0_iter14_reg;
reg   [0:0] x_is_1_reg_2268_pp0_iter15_reg;
reg   [0:0] x_is_1_reg_2268_pp0_iter16_reg;
wire   [0:0] x_is_p1_fu_624_p2;
reg   [0:0] x_is_p1_reg_2275;
reg   [0:0] x_is_p1_reg_2275_pp0_iter1_reg;
reg   [0:0] x_is_p1_reg_2275_pp0_iter2_reg;
reg   [0:0] x_is_p1_reg_2275_pp0_iter3_reg;
reg   [0:0] x_is_p1_reg_2275_pp0_iter4_reg;
reg   [0:0] x_is_p1_reg_2275_pp0_iter5_reg;
reg   [0:0] x_is_p1_reg_2275_pp0_iter6_reg;
reg   [0:0] x_is_p1_reg_2275_pp0_iter7_reg;
reg   [0:0] x_is_p1_reg_2275_pp0_iter8_reg;
reg   [0:0] x_is_p1_reg_2275_pp0_iter9_reg;
reg   [0:0] x_is_p1_reg_2275_pp0_iter10_reg;
reg   [0:0] x_is_p1_reg_2275_pp0_iter11_reg;
reg   [0:0] x_is_p1_reg_2275_pp0_iter12_reg;
reg   [0:0] x_is_p1_reg_2275_pp0_iter13_reg;
reg   [0:0] x_is_p1_reg_2275_pp0_iter14_reg;
reg   [0:0] x_is_p1_reg_2275_pp0_iter15_reg;
reg   [0:0] x_is_p1_reg_2275_pp0_iter16_reg;
wire   [0:0] icmp_ln828_1_fu_630_p2;
reg   [0:0] icmp_ln828_1_reg_2281;
reg   [0:0] icmp_ln828_1_reg_2281_pp0_iter1_reg;
reg   [0:0] icmp_ln828_1_reg_2281_pp0_iter2_reg;
reg   [0:0] icmp_ln828_1_reg_2281_pp0_iter3_reg;
reg   [0:0] icmp_ln828_1_reg_2281_pp0_iter4_reg;
reg   [0:0] icmp_ln828_1_reg_2281_pp0_iter5_reg;
reg   [0:0] icmp_ln828_1_reg_2281_pp0_iter6_reg;
reg   [0:0] icmp_ln828_1_reg_2281_pp0_iter7_reg;
reg   [0:0] icmp_ln828_1_reg_2281_pp0_iter8_reg;
reg   [0:0] icmp_ln828_1_reg_2281_pp0_iter9_reg;
reg   [0:0] icmp_ln828_1_reg_2281_pp0_iter10_reg;
reg   [0:0] icmp_ln828_1_reg_2281_pp0_iter11_reg;
reg   [0:0] icmp_ln828_1_reg_2281_pp0_iter12_reg;
reg   [0:0] icmp_ln828_1_reg_2281_pp0_iter13_reg;
reg   [0:0] icmp_ln828_1_reg_2281_pp0_iter14_reg;
reg   [0:0] icmp_ln828_1_reg_2281_pp0_iter15_reg;
reg   [0:0] icmp_ln828_1_reg_2281_pp0_iter16_reg;
wire   [0:0] p_Result_s_fu_636_p3;
reg   [0:0] p_Result_s_reg_2287;
wire   [11:0] b_exp_2_fu_660_p3;
reg   [11:0] b_exp_2_reg_2292;
reg   [11:0] b_exp_2_reg_2292_pp0_iter1_reg;
reg   [11:0] b_exp_2_reg_2292_pp0_iter2_reg;
reg   [11:0] b_exp_2_reg_2292_pp0_iter3_reg;
reg   [11:0] b_exp_2_reg_2292_pp0_iter4_reg;
reg   [11:0] b_exp_2_reg_2292_pp0_iter5_reg;
reg   [11:0] b_exp_2_reg_2292_pp0_iter6_reg;
reg   [11:0] b_exp_2_reg_2292_pp0_iter7_reg;
reg  signed [11:0] b_exp_2_reg_2292_pp0_iter8_reg;
wire   [63:0] zext_ln492_fu_668_p1;
reg   [63:0] zext_ln492_reg_2297;
reg   [63:0] zext_ln492_reg_2297_pp0_iter1_reg;
reg   [63:0] zext_ln492_reg_2297_pp0_iter2_reg;
reg   [63:0] zext_ln492_reg_2297_pp0_iter3_reg;
reg   [63:0] zext_ln492_reg_2297_pp0_iter4_reg;
reg   [63:0] zext_ln492_reg_2297_pp0_iter5_reg;
reg   [63:0] zext_ln492_reg_2297_pp0_iter6_reg;
reg   [63:0] zext_ln492_reg_2297_pp0_iter7_reg;
wire   [0:0] and_ln407_1_fu_697_p2;
reg   [0:0] and_ln407_1_reg_2307;
reg   [0:0] and_ln407_1_reg_2307_pp0_iter1_reg;
reg   [0:0] and_ln407_1_reg_2307_pp0_iter2_reg;
reg   [0:0] and_ln407_1_reg_2307_pp0_iter3_reg;
reg   [0:0] and_ln407_1_reg_2307_pp0_iter4_reg;
reg   [0:0] and_ln407_1_reg_2307_pp0_iter5_reg;
reg   [0:0] and_ln407_1_reg_2307_pp0_iter6_reg;
reg   [0:0] and_ln407_1_reg_2307_pp0_iter7_reg;
reg   [0:0] and_ln407_1_reg_2307_pp0_iter8_reg;
reg   [0:0] and_ln407_1_reg_2307_pp0_iter9_reg;
reg   [0:0] and_ln407_1_reg_2307_pp0_iter10_reg;
reg   [0:0] and_ln407_1_reg_2307_pp0_iter11_reg;
reg   [0:0] and_ln407_1_reg_2307_pp0_iter12_reg;
reg   [0:0] and_ln407_1_reg_2307_pp0_iter13_reg;
reg   [0:0] and_ln407_1_reg_2307_pp0_iter14_reg;
reg   [0:0] and_ln407_1_reg_2307_pp0_iter15_reg;
reg   [0:0] and_ln407_1_reg_2307_pp0_iter16_reg;
wire   [0:0] sel_tmp13_fu_715_p2;
reg   [0:0] sel_tmp13_reg_2313;
reg   [0:0] sel_tmp13_reg_2313_pp0_iter1_reg;
reg   [0:0] sel_tmp13_reg_2313_pp0_iter2_reg;
reg   [0:0] sel_tmp13_reg_2313_pp0_iter3_reg;
reg   [0:0] sel_tmp13_reg_2313_pp0_iter4_reg;
reg   [0:0] sel_tmp13_reg_2313_pp0_iter5_reg;
reg   [0:0] sel_tmp13_reg_2313_pp0_iter6_reg;
reg   [0:0] sel_tmp13_reg_2313_pp0_iter7_reg;
reg   [0:0] sel_tmp13_reg_2313_pp0_iter8_reg;
reg   [0:0] sel_tmp13_reg_2313_pp0_iter9_reg;
reg   [0:0] sel_tmp13_reg_2313_pp0_iter10_reg;
reg   [0:0] sel_tmp13_reg_2313_pp0_iter11_reg;
reg   [0:0] sel_tmp13_reg_2313_pp0_iter12_reg;
reg   [0:0] sel_tmp13_reg_2313_pp0_iter13_reg;
reg   [0:0] sel_tmp13_reg_2313_pp0_iter14_reg;
reg   [0:0] sel_tmp13_reg_2313_pp0_iter15_reg;
reg   [0:0] sel_tmp13_reg_2313_pp0_iter16_reg;
wire   [53:0] mul_ln682_fu_752_p2;
reg   [53:0] mul_ln682_reg_2319;
reg   [3:0] a_reg_2326;
reg   [3:0] a_reg_2326_pp0_iter2_reg;
reg   [3:0] a_reg_2326_pp0_iter3_reg;
reg   [3:0] a_reg_2326_pp0_iter4_reg;
reg   [3:0] a_reg_2326_pp0_iter5_reg;
reg   [3:0] a_reg_2326_pp0_iter6_reg;
reg   [3:0] a_reg_2326_pp0_iter7_reg;
wire   [49:0] trunc_ln657_fu_768_p1;
reg   [49:0] trunc_ln657_reg_2332;
reg   [0:0] tmp_6_reg_2337;
reg   [72:0] z2_V_reg_2342;
reg   [5:0] a_1_reg_2348;
reg   [5:0] a_1_reg_2348_pp0_iter3_reg;
reg   [5:0] a_1_reg_2348_pp0_iter4_reg;
reg   [5:0] a_1_reg_2348_pp0_iter5_reg;
reg   [5:0] a_1_reg_2348_pp0_iter6_reg;
reg   [5:0] a_1_reg_2348_pp0_iter7_reg;
reg   [66:0] tmp_4_reg_2354;
wire   [81:0] ret_V_5_fu_938_p2;
reg   [81:0] ret_V_5_reg_2359;
reg   [5:0] a_2_reg_2365;
reg   [5:0] a_2_reg_2365_pp0_iter4_reg;
reg   [5:0] a_2_reg_2365_pp0_iter5_reg;
reg   [5:0] a_2_reg_2365_pp0_iter6_reg;
reg   [5:0] a_2_reg_2365_pp0_iter7_reg;
wire   [75:0] trunc_ln657_3_fu_954_p1;
reg   [75:0] trunc_ln657_3_reg_2371;
reg   [91:0] z4_V_reg_2376;
reg   [85:0] tmp_8_reg_2382;
reg   [5:0] tmp_9_reg_2387;
reg   [5:0] tmp_9_reg_2387_pp0_iter5_reg;
reg   [5:0] tmp_9_reg_2387_pp0_iter6_reg;
reg   [5:0] tmp_9_reg_2387_pp0_iter7_reg;
reg   [86:0] z5_V_reg_2393;
reg   [80:0] tmp_s_reg_2399;
reg   [5:0] tmp_2_reg_2404;
reg   [5:0] tmp_2_reg_2404_pp0_iter6_reg;
reg   [5:0] tmp_2_reg_2404_pp0_iter7_reg;
reg   [81:0] z6_V_reg_2410;
reg   [75:0] tmp_5_reg_2416;
reg   [5:0] tmp_7_reg_2421;
reg   [5:0] tmp_7_reg_2421_pp0_iter7_reg;
reg   [76:0] z7_V_reg_2427;
reg   [70:0] tmp_10_reg_2433;
reg   [5:0] tmp_11_reg_2438;
reg   [71:0] tmp_12_reg_2484;
reg   [39:0] tmp_13_reg_2489;
wire   [119:0] ret_V_17_fu_1589_p2;
reg   [119:0] ret_V_17_reg_2494;
reg   [119:0] ret_V_17_reg_2494_pp0_iter10_reg;
reg   [119:0] ret_V_17_reg_2494_pp0_iter11_reg;
reg   [119:0] ret_V_17_reg_2494_pp0_iter12_reg;
reg   [119:0] ret_V_17_reg_2494_pp0_iter13_reg;
reg   [119:0] ret_V_17_reg_2494_pp0_iter14_reg;
reg   [119:0] ret_V_17_reg_2494_pp0_iter15_reg;
reg   [0:0] p_Result_16_reg_2499;
reg   [0:0] p_Result_16_reg_2499_pp0_iter10_reg;
reg   [58:0] trunc_ln2_reg_2509;
reg   [58:0] trunc_ln2_reg_2509_pp0_iter10_reg;
reg   [58:0] trunc_ln2_reg_2509_pp0_iter11_reg;
reg   [58:0] trunc_ln2_reg_2509_pp0_iter12_reg;
wire  signed [12:0] r_exp_V_fu_1677_p3;
reg  signed [12:0] r_exp_V_reg_2519;
reg  signed [12:0] r_exp_V_reg_2519_pp0_iter13_reg;
reg  signed [12:0] r_exp_V_reg_2519_pp0_iter14_reg;
reg  signed [12:0] r_exp_V_reg_2519_pp0_iter15_reg;
reg   [7:0] m_diff_hi_V_reg_2526;
reg   [7:0] Z2_reg_2531;
reg   [7:0] Z2_reg_2531_pp0_iter14_reg;
wire   [7:0] Z3_fu_1729_p4;
reg   [7:0] Z3_reg_2538;
wire   [34:0] Z4_fu_1739_p1;
reg   [34:0] Z4_reg_2543;
wire   [42:0] ret_V_34_fu_1790_p4;
reg   [42:0] ret_V_34_reg_2563;
wire   [35:0] add_ln657_7_fu_1827_p2;
reg   [35:0] add_ln657_7_reg_2568;
reg   [57:0] exp_Z1_V_reg_2578;
reg   [49:0] exp_Z1P_m_1_V_reg_2583;
reg   [49:0] exp_Z1_hi_V_reg_2588;
wire   [0:0] icmp_ln844_fu_2056_p2;
reg   [0:0] icmp_ln844_reg_2593;
wire   [0:0] icmp_ln848_fu_2077_p2;
reg   [0:0] icmp_ln848_reg_2598;
wire   [63:0] select_ln657_fu_2140_p3;
reg   [63:0] select_ln657_reg_2603;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln492_1_fu_1320_p1;
wire   [63:0] zext_ln492_6_fu_1324_p1;
wire   [63:0] zext_ln492_7_fu_1328_p1;
wire   [63:0] zext_ln492_8_fu_1332_p1;
wire   [63:0] zext_ln492_9_fu_1336_p1;
wire   [63:0] zext_ln492_10_fu_1340_p1;
wire   [63:0] zext_ln492_11_fu_1402_p1;
wire   [63:0] zext_ln492_3_fu_1753_p1;
wire   [63:0] zext_ln492_4_fu_1758_p1;
wire   [63:0] zext_ln492_2_fu_1763_p1;
wire   [63:0] zext_ln492_5_fu_1833_p1;
wire   [63:0] p_Val2_s_fu_564_p1;
wire   [10:0] p_Repl2_3_fu_576_p4;
wire   [11:0] zext_ln509_fu_590_p1;
wire   [11:0] b_exp_fu_594_p2;
wire   [0:0] icmp_ln369_fu_600_p2;
wire   [0:0] p_Result_14_fu_568_p3;
wire   [0:0] xor_ln964_fu_618_p2;
wire   [11:0] b_exp_1_fu_654_p2;
wire   [5:0] index0_V_fu_644_p4;
wire   [0:0] icmp_ln407_1_fu_685_p2;
wire   [0:0] xor_ln369_fu_673_p2;
wire   [0:0] and_ln407_fu_691_p2;
wire   [0:0] icmp_ln407_fu_679_p2;
wire   [0:0] icmp_ln407_2_fu_703_p2;
wire   [0:0] or_ln407_3_fu_709_p2;
wire   [52:0] b_frac_fu_730_p3;
wire   [53:0] zext_ln1287_1_fu_737_p1;
wire   [53:0] p_Result_15_fu_721_p4;
wire   [5:0] mul_ln682_fu_752_p0;
wire  signed [53:0] mul_ln682_fu_752_p1;
wire   [74:0] sf_fu_787_p4;
wire   [75:0] tmp_3_fu_796_p4;
wire   [75:0] zext_ln1287_fu_805_p1;
wire   [74:0] lhs_V_1_fu_816_p3;
wire   [75:0] select_ln1287_fu_809_p3;
wire   [75:0] zext_ln1146_fu_823_p1;
wire   [70:0] z1_V_fu_780_p3;
wire   [3:0] r_V_13_fu_840_p0;
wire   [70:0] r_V_13_fu_840_p1;
wire   [74:0] r_V_13_fu_840_p2;
wire   [75:0] ret_V_25_fu_827_p2;
wire   [75:0] zext_ln1147_fu_846_p1;
wire   [75:0] ret_V_3_fu_850_p2;
wire   [80:0] lhs_V_3_fu_893_p3;
wire   [80:0] eZ_V_fu_886_p3;
wire   [81:0] zext_ln657_fu_904_p1;
wire   [81:0] zext_ln1146_1_fu_900_p1;
wire   [5:0] r_V_2_fu_920_p0;
wire   [72:0] r_V_2_fu_920_p1;
wire   [78:0] r_V_2_fu_920_p2;
wire   [79:0] rhs_V_2_fu_926_p3;
wire   [81:0] ret_V_26_fu_908_p2;
wire   [81:0] zext_ln1147_1_fu_934_p1;
wire   [100:0] lhs_V_5_fu_974_p3;
wire   [95:0] eZ_V_1_fu_965_p4;
wire   [101:0] zext_ln657_1_fu_985_p1;
wire   [101:0] zext_ln1146_2_fu_981_p1;
wire   [82:0] z3_V_fu_958_p3;
wire   [5:0] r_V_3_fu_1002_p0;
wire   [82:0] r_V_3_fu_1002_p1;
wire   [88:0] r_V_3_fu_1002_p2;
wire   [94:0] rhs_V_4_fu_1008_p3;
wire   [101:0] ret_V_27_fu_989_p2;
wire   [101:0] zext_ln1147_2_fu_1016_p1;
wire   [101:0] ret_V_7_fu_1020_p2;
wire   [119:0] lhs_V_7_fu_1063_p3;
wire   [109:0] eZ_V_2_fu_1056_p3;
wire   [120:0] zext_ln657_2_fu_1074_p1;
wire   [120:0] zext_ln1146_3_fu_1070_p1;
wire   [5:0] r_V_4_fu_1090_p0;
wire   [91:0] r_V_4_fu_1090_p1;
wire   [97:0] r_V_4_fu_1090_p2;
wire   [108:0] rhs_V_6_fu_1096_p3;
wire   [120:0] ret_V_28_fu_1078_p2;
wire   [120:0] zext_ln1147_3_fu_1104_p1;
wire   [120:0] ret_V_9_fu_1108_p2;
wire   [124:0] lhs_V_9_fu_1151_p3;
wire   [109:0] eZ_V_3_fu_1144_p3;
wire   [125:0] zext_ln657_3_fu_1162_p1;
wire   [125:0] zext_ln1146_4_fu_1158_p1;
wire   [5:0] r_V_5_fu_1178_p0;
wire   [86:0] r_V_5_fu_1178_p1;
wire   [92:0] r_V_5_fu_1178_p2;
wire   [108:0] rhs_V_8_fu_1184_p3;
wire   [125:0] ret_V_29_fu_1166_p2;
wire   [125:0] zext_ln1147_4_fu_1192_p1;
wire   [125:0] ret_V_11_fu_1196_p2;
wire   [129:0] lhs_V_11_fu_1239_p3;
wire   [109:0] eZ_V_4_fu_1232_p3;
wire   [130:0] zext_ln657_4_fu_1250_p1;
wire   [130:0] zext_ln1146_5_fu_1246_p1;
wire   [5:0] r_V_6_fu_1266_p0;
wire   [81:0] r_V_6_fu_1266_p1;
wire   [87:0] r_V_6_fu_1266_p2;
wire   [108:0] rhs_V_10_fu_1272_p3;
wire   [130:0] ret_V_30_fu_1254_p2;
wire   [130:0] zext_ln1147_5_fu_1280_p1;
wire   [130:0] ret_V_13_fu_1284_p2;
wire   [134:0] lhs_V_13_fu_1351_p3;
wire   [109:0] eZ_V_5_fu_1344_p3;
wire   [135:0] zext_ln657_5_fu_1362_p1;
wire   [135:0] zext_ln1146_6_fu_1358_p1;
wire   [5:0] r_V_7_fu_1378_p0;
wire   [76:0] r_V_7_fu_1378_p1;
wire   [82:0] r_V_7_fu_1378_p2;
wire   [108:0] rhs_V_12_fu_1384_p3;
wire   [135:0] ret_V_31_fu_1366_p2;
wire   [135:0] zext_ln1147_6_fu_1392_p1;
wire   [135:0] ret_V_15_fu_1396_p2;
wire   [79:0] Elog2_V_fu_1429_p1;
wire   [108:0] zext_ln223_fu_1435_p1;
wire   [102:0] zext_ln223_2_fu_1443_p1;
wire   [102:0] zext_ln223_1_fu_1439_p1;
wire   [102:0] add_ln657_1_fu_1469_p2;
wire   [108:0] add_ln657_fu_1463_p2;
wire   [108:0] zext_ln657_6_fu_1475_p1;
wire   [92:0] zext_ln223_4_fu_1451_p1;
wire   [92:0] zext_ln223_3_fu_1447_p1;
wire   [82:0] zext_ln223_6_fu_1459_p1;
wire   [82:0] zext_ln223_5_fu_1455_p1;
wire   [82:0] add_ln657_4_fu_1491_p2;
wire   [92:0] add_ln657_3_fu_1485_p2;
wire   [92:0] zext_ln657_7_fu_1497_p1;
wire   [92:0] add_ln657_5_fu_1501_p2;
wire   [108:0] add_ln657_2_fu_1479_p2;
wire   [108:0] zext_ln657_8_fu_1507_p1;
wire   [39:0] r_V_14_fu_1520_p0;
wire   [79:0] zext_ln1072_12_fu_1517_p1;
wire   [39:0] r_V_14_fu_1520_p1;
wire   [79:0] r_V_14_fu_1520_p2;
wire   [116:0] lhs_V_fu_1536_p3;
wire   [78:0] rhs_V_s_fu_1526_p4;
wire   [117:0] zext_ln1147_7_fu_1543_p1;
wire   [117:0] zext_ln1147_8_fu_1547_p1;
wire   [117:0] ret_V_fu_1551_p2;
wire   [89:0] Elog2_V_fu_1429_p2;
wire   [108:0] log_sum_V_1_fu_1511_p2;
wire  signed [119:0] sext_ln1146_fu_1575_p1;
wire   [119:0] lhs_V_15_fu_1567_p3;
wire   [72:0] trunc_ln1_fu_1557_p4;
wire  signed [119:0] sext_ln1146_1_fu_1585_p1;
wire   [119:0] ret_V_16_fu_1579_p2;
wire  signed [15:0] m_fix_hi_V_fu_1595_p4;
wire  signed [18:0] rhs_V_13_fu_1627_p3;
wire  signed [30:0] grp_fu_2246_p3;
wire   [17:0] trunc_ln805_fu_1654_p1;
wire   [12:0] p_Result_cast_fu_1638_p4;
wire   [0:0] icmp_ln805_fu_1657_p2;
wire   [12:0] add_ln649_fu_1663_p2;
wire   [0:0] p_Result_7_fu_1647_p3;
wire   [12:0] select_ln804_fu_1669_p3;
wire   [70:0] r_V_fu_1688_p2;
wire   [58:0] trunc_ln657_1_fu_1694_p4;
wire   [58:0] m_diff_fu_1704_p2;
wire   [7:0] Z4_ind_V_fu_1743_p4;
wire   [9:0] f_Z4_V_fu_1767_p4;
wire   [35:0] zext_ln657_10_fu_1780_p1;
wire   [35:0] zext_ln657_9_fu_1777_p1;
wire   [35:0] ret_V_33_fu_1784_p2;
wire   [35:0] r_V_10_fu_1807_p0;
wire   [42:0] r_V_10_fu_1807_p1;
wire   [78:0] r_V_10_fu_1807_p2;
wire   [19:0] trunc_ln657_s_fu_1813_p4;
wire   [35:0] zext_ln657_11_fu_1823_p1;
wire   [43:0] zext_ln1146_7_fu_1837_p1;
wire   [43:0] zext_ln657_12_fu_1840_p1;
wire   [39:0] tmp_14_fu_1849_p4;
wire   [48:0] exp_Z2_m_1_V_fu_1859_p4;
wire   [43:0] exp_Z2P_m_1_V_fu_1843_p2;
wire   [43:0] r_V_11_fu_1876_p0;
wire   [48:0] r_V_11_fu_1876_p1;
wire   [50:0] lhs_V_18_fu_1882_p5;
wire   [92:0] r_V_11_fu_1876_p2;
wire   [35:0] trunc_ln657_2_fu_1897_p4;
wire   [43:0] zext_ln657_13_fu_1907_p1;
wire   [43:0] add_ln657_9_fu_1911_p2;
wire   [51:0] zext_ln1146_8_fu_1893_p1;
wire   [51:0] zext_ln657_14_fu_1917_p1;
wire   [51:0] exp_Z1P_m_1_l_V_fu_1921_p2;
wire   [49:0] r_V_16_fu_1958_p0;
wire   [49:0] r_V_16_fu_1958_p1;
wire   [57:0] ret_V_23_fu_1947_p2;
wire   [99:0] r_V_16_fu_1958_p2;
wire   [56:0] trunc_ln1146_fu_1980_p1;
wire   [55:0] trunc_ln1146_2_fu_1996_p1;
wire   [106:0] zext_ln1146_9_fu_1972_p1;
wire   [106:0] lhs_V_20_fu_1964_p3;
wire   [104:0] trunc_ln1146_1_fu_2000_p3;
wire   [104:0] zext_ln1146_11_fu_1992_p1;
wire   [105:0] trunc_ln3_fu_1984_p3;
wire   [105:0] zext_ln1146_10_fu_1976_p1;
wire   [106:0] ret_V_24_fu_2008_p2;
wire   [0:0] tmp_16_fu_2026_p3;
wire   [12:0] r_exp_V_1_fu_2034_p2;
wire   [12:0] select_ln651_fu_2039_p3;
wire   [2:0] tmp_17_fu_2046_p4;
wire   [0:0] tmp_18_fu_2062_p3;
wire   [105:0] add_ln1146_2_fu_2020_p2;
wire   [104:0] add_ln1146_1_fu_2014_p2;
wire   [51:0] tmp_fu_2083_p4;
wire   [51:0] tmp_1_fu_2093_p4;
wire   [10:0] trunc_ln170_fu_2111_p1;
wire   [10:0] p_Val2_11_fu_2115_p2;
wire   [51:0] tmp_V_fu_2103_p3;
wire   [63:0] p_Result_13_fu_2121_p4;
wire   [0:0] and_ln657_fu_2135_p2;
wire   [63:0] select_ln658_fu_2069_p3;
wire   [63:0] bitcast_ln520_fu_2131_p1;
wire   [0:0] xor_ln832_fu_2148_p2;
wire   [0:0] x_is_NaN_fu_2153_p2;
wire   [0:0] or_ln407_fu_2158_p2;
wire   [63:0] select_ln407_fu_2163_p3;
wire   [0:0] or_ln407_1_fu_2170_p2;
wire   [63:0] select_ln407_1_fu_2175_p3;
wire   [0:0] or_ln407_2_fu_2183_p2;
wire   [63:0] select_ln407_2_fu_2187_p3;
wire   [63:0] select_ln407_3_fu_2195_p3;
wire   [0:0] xor_ln657_fu_2209_p2;
wire   [0:0] and_ln848_fu_2214_p2;
wire   [0:0] and_ln848_1_fu_2219_p2;
wire   [63:0] sel_tmp14_fu_2203_p3;
wire   [63:0] select_ln848_fu_2224_p3;
wire   [63:0] select_ln369_fu_2232_p3;
wire   [15:0] grp_fu_2246_p1;
reg    grp_fu_2246_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to16;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [53:0] mul_ln682_fu_752_p00;
wire   [78:0] r_V_10_fu_1807_p00;
wire   [78:0] r_V_10_fu_1807_p10;
wire   [92:0] r_V_11_fu_1876_p00;
wire   [92:0] r_V_11_fu_1876_p10;
wire   [74:0] r_V_13_fu_840_p00;
wire   [74:0] r_V_13_fu_840_p10;
wire   [99:0] r_V_16_fu_1958_p00;
wire   [99:0] r_V_16_fu_1958_p10;
wire   [78:0] r_V_2_fu_920_p00;
wire   [78:0] r_V_2_fu_920_p10;
wire   [88:0] r_V_3_fu_1002_p00;
wire   [88:0] r_V_3_fu_1002_p10;
wire   [97:0] r_V_4_fu_1090_p00;
wire   [97:0] r_V_4_fu_1090_p10;
wire   [92:0] r_V_5_fu_1178_p00;
wire   [92:0] r_V_5_fu_1178_p10;
wire   [87:0] r_V_6_fu_1266_p00;
wire   [87:0] r_V_6_fu_1266_p10;
wire   [82:0] r_V_7_fu_1378_p00;
wire   [82:0] r_V_7_fu_1378_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
end

farthest_point_sampling_pow_generic_double_s_pow_reduce_anonymous_namespace_log_inverse_lut_table_powbkb #(
    .DataWidth( 6 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_V_address0),
    .ce0(pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_V_ce0),
    .q0(pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_V_q0)
);

farthest_point_sampling_pow_generic_double_s_pow_reduce_anonymous_namespace_log0_lut_table_ap_fixed_1cud #(
    .DataWidth( 109 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pow_reduce_anonymous_namespace_log0_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_double_0_5_64_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_log0_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_double_0_5_64_array_V_address0),
    .ce0(pow_reduce_anonymous_namespace_log0_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_double_0_5_64_array_V_ce0),
    .q0(pow_reduce_anonymous_namespace_log0_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_double_0_5_64_array_V_q0)
);

farthest_point_sampling_pow_generic_double_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12dEe #(
    .DataWidth( 105 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_4_4_16_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_4_4_16_array_V_address0),
    .ce0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_4_4_16_array_V_ce0),
    .q0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_4_4_16_array_V_q0)
);

farthest_point_sampling_pow_generic_double_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12eOg #(
    .DataWidth( 102 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_7_6_64_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_7_6_64_array_V_address0),
    .ce0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_7_6_64_array_V_ce0),
    .q0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_7_6_64_array_V_q0)
);

farthest_point_sampling_pow_generic_double_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12fYi #(
    .DataWidth( 97 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_12_6_64_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_12_6_64_array_V_address0),
    .ce0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_12_6_64_array_V_ce0),
    .q0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_12_6_64_array_V_q0)
);

farthest_point_sampling_pow_generic_double_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12g8j #(
    .DataWidth( 92 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_17_6_64_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_17_6_64_array_V_address0),
    .ce0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_17_6_64_array_V_ce0),
    .q0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_17_6_64_array_V_q0)
);

farthest_point_sampling_pow_generic_double_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12hbi #(
    .DataWidth( 87 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_22_6_64_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_22_6_64_array_V_address0),
    .ce0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_22_6_64_array_V_ce0),
    .q0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_22_6_64_array_V_q0)
);

farthest_point_sampling_pow_generic_double_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12ibs #(
    .DataWidth( 82 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_27_6_64_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_27_6_64_array_V_address0),
    .ce0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_27_6_64_array_V_ce0),
    .q0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_27_6_64_array_V_q0)
);

farthest_point_sampling_pow_generic_double_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12jbC #(
    .DataWidth( 77 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_32_6_64_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_32_6_64_array_V_address0),
    .ce0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_32_6_64_array_V_ce0),
    .q0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_32_6_64_array_V_q0)
);

farthest_point_sampling_pow_generic_double_s_pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_58kbM #(
    .DataWidth( 58 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0),
    .ce0(pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0),
    .q0(pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0)
);

farthest_point_sampling_pow_generic_double_s_pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0lbW #(
    .DataWidth( 26 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0),
    .ce0(pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0),
    .q0(pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0),
    .address1(pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address1),
    .ce1(pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce1),
    .q1(pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q1)
);

farthest_point_sampling_pow_generic_double_s_pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_59_0mb6 #(
    .DataWidth( 42 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0),
    .ce0(pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0),
    .q0(pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0)
);

farthest_point_sampling_mul_6ns_54s_54_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 54 ),
    .dout_WIDTH( 54 ))
mul_6ns_54s_54_1_1_U1(
    .din0(mul_ln682_fu_752_p0),
    .din1(mul_ln682_fu_752_p1),
    .dout(mul_ln682_fu_752_p2)
);

farthest_point_sampling_mul_4ns_71ns_75_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 71 ),
    .dout_WIDTH( 75 ))
mul_4ns_71ns_75_1_1_U2(
    .din0(r_V_13_fu_840_p0),
    .din1(r_V_13_fu_840_p1),
    .dout(r_V_13_fu_840_p2)
);

farthest_point_sampling_mul_6ns_73ns_79_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 73 ),
    .dout_WIDTH( 79 ))
mul_6ns_73ns_79_1_1_U3(
    .din0(r_V_2_fu_920_p0),
    .din1(r_V_2_fu_920_p1),
    .dout(r_V_2_fu_920_p2)
);

farthest_point_sampling_mul_6ns_83ns_89_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 83 ),
    .dout_WIDTH( 89 ))
mul_6ns_83ns_89_1_1_U4(
    .din0(r_V_3_fu_1002_p0),
    .din1(r_V_3_fu_1002_p1),
    .dout(r_V_3_fu_1002_p2)
);

farthest_point_sampling_mul_6ns_92ns_98_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 92 ),
    .dout_WIDTH( 98 ))
mul_6ns_92ns_98_1_1_U5(
    .din0(r_V_4_fu_1090_p0),
    .din1(r_V_4_fu_1090_p1),
    .dout(r_V_4_fu_1090_p2)
);

farthest_point_sampling_mul_6ns_87ns_93_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 87 ),
    .dout_WIDTH( 93 ))
mul_6ns_87ns_93_1_1_U6(
    .din0(r_V_5_fu_1178_p0),
    .din1(r_V_5_fu_1178_p1),
    .dout(r_V_5_fu_1178_p2)
);

farthest_point_sampling_mul_6ns_82ns_88_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 82 ),
    .dout_WIDTH( 88 ))
mul_6ns_82ns_88_1_1_U7(
    .din0(r_V_6_fu_1266_p0),
    .din1(r_V_6_fu_1266_p1),
    .dout(r_V_6_fu_1266_p2)
);

farthest_point_sampling_mul_6ns_77ns_83_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 77 ),
    .dout_WIDTH( 83 ))
mul_6ns_77ns_83_1_1_U8(
    .din0(r_V_7_fu_1378_p0),
    .din1(r_V_7_fu_1378_p1),
    .dout(r_V_7_fu_1378_p2)
);

farthest_point_sampling_mul_12s_80ns_90_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 80 ),
    .dout_WIDTH( 90 ))
mul_12s_80ns_90_1_1_U9(
    .din0(b_exp_2_reg_2292_pp0_iter8_reg),
    .din1(Elog2_V_fu_1429_p1),
    .dout(Elog2_V_fu_1429_p2)
);

farthest_point_sampling_mul_40ns_40ns_80_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 40 ),
    .dout_WIDTH( 80 ))
mul_40ns_40ns_80_1_1_U10(
    .din0(r_V_14_fu_1520_p0),
    .din1(r_V_14_fu_1520_p1),
    .dout(r_V_14_fu_1520_p2)
);

farthest_point_sampling_mul_13s_71s_71_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 71 ),
    .dout_WIDTH( 71 ))
mul_13s_71s_71_1_1_U11(
    .din0(r_exp_V_reg_2519),
    .din1(71'd1636647506585939924452),
    .dout(r_V_fu_1688_p2)
);

farthest_point_sampling_mul_36ns_43ns_79_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 36 ),
    .din1_WIDTH( 43 ),
    .dout_WIDTH( 79 ))
mul_36ns_43ns_79_1_1_U12(
    .din0(r_V_10_fu_1807_p0),
    .din1(r_V_10_fu_1807_p1),
    .dout(r_V_10_fu_1807_p2)
);

farthest_point_sampling_mul_44ns_49ns_93_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 44 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 93 ))
mul_44ns_49ns_93_1_1_U13(
    .din0(r_V_11_fu_1876_p0),
    .din1(r_V_11_fu_1876_p1),
    .dout(r_V_11_fu_1876_p2)
);

farthest_point_sampling_mul_50ns_50ns_100_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 100 ))
mul_50ns_50ns_100_1_1_U14(
    .din0(r_V_16_fu_1958_p0),
    .din1(r_V_16_fu_1958_p1),
    .dout(r_V_16_fu_1958_p2)
);

farthest_point_sampling_mac_muladd_16s_16ns_19s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_16ns_19s_31_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(m_fix_hi_V_fu_1595_p4),
    .din1(grp_fu_2246_p1),
    .din2(rhs_V_13_fu_1627_p3),
    .ce(grp_fu_2246_ce),
    .dout(grp_fu_2246_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((sel_tmp13_reg_2313_pp0_iter12_reg == 1'd0) & (x_is_1_reg_2268_pp0_iter12_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        Z2_reg_2531 <= {{m_diff_fu_1704_p2[50:43]}};
        Z3_reg_2538 <= {{m_diff_fu_1704_p2[42:35]}};
        Z4_reg_2543 <= Z4_fu_1739_p1;
        m_diff_hi_V_reg_2526 <= {{m_diff_fu_1704_p2[58:51]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        Z2_reg_2531_pp0_iter14_reg <= Z2_reg_2531;
        a_1_reg_2348_pp0_iter3_reg <= a_1_reg_2348;
        a_1_reg_2348_pp0_iter4_reg <= a_1_reg_2348_pp0_iter3_reg;
        a_1_reg_2348_pp0_iter5_reg <= a_1_reg_2348_pp0_iter4_reg;
        a_1_reg_2348_pp0_iter6_reg <= a_1_reg_2348_pp0_iter5_reg;
        a_1_reg_2348_pp0_iter7_reg <= a_1_reg_2348_pp0_iter6_reg;
        a_2_reg_2365_pp0_iter4_reg <= a_2_reg_2365;
        a_2_reg_2365_pp0_iter5_reg <= a_2_reg_2365_pp0_iter4_reg;
        a_2_reg_2365_pp0_iter6_reg <= a_2_reg_2365_pp0_iter5_reg;
        a_2_reg_2365_pp0_iter7_reg <= a_2_reg_2365_pp0_iter6_reg;
        a_reg_2326_pp0_iter2_reg <= a_reg_2326;
        a_reg_2326_pp0_iter3_reg <= a_reg_2326_pp0_iter2_reg;
        a_reg_2326_pp0_iter4_reg <= a_reg_2326_pp0_iter3_reg;
        a_reg_2326_pp0_iter5_reg <= a_reg_2326_pp0_iter4_reg;
        a_reg_2326_pp0_iter6_reg <= a_reg_2326_pp0_iter5_reg;
        a_reg_2326_pp0_iter7_reg <= a_reg_2326_pp0_iter6_reg;
        and_ln407_1_reg_2307_pp0_iter10_reg <= and_ln407_1_reg_2307_pp0_iter9_reg;
        and_ln407_1_reg_2307_pp0_iter11_reg <= and_ln407_1_reg_2307_pp0_iter10_reg;
        and_ln407_1_reg_2307_pp0_iter12_reg <= and_ln407_1_reg_2307_pp0_iter11_reg;
        and_ln407_1_reg_2307_pp0_iter13_reg <= and_ln407_1_reg_2307_pp0_iter12_reg;
        and_ln407_1_reg_2307_pp0_iter14_reg <= and_ln407_1_reg_2307_pp0_iter13_reg;
        and_ln407_1_reg_2307_pp0_iter15_reg <= and_ln407_1_reg_2307_pp0_iter14_reg;
        and_ln407_1_reg_2307_pp0_iter16_reg <= and_ln407_1_reg_2307_pp0_iter15_reg;
        and_ln407_1_reg_2307_pp0_iter2_reg <= and_ln407_1_reg_2307_pp0_iter1_reg;
        and_ln407_1_reg_2307_pp0_iter3_reg <= and_ln407_1_reg_2307_pp0_iter2_reg;
        and_ln407_1_reg_2307_pp0_iter4_reg <= and_ln407_1_reg_2307_pp0_iter3_reg;
        and_ln407_1_reg_2307_pp0_iter5_reg <= and_ln407_1_reg_2307_pp0_iter4_reg;
        and_ln407_1_reg_2307_pp0_iter6_reg <= and_ln407_1_reg_2307_pp0_iter5_reg;
        and_ln407_1_reg_2307_pp0_iter7_reg <= and_ln407_1_reg_2307_pp0_iter6_reg;
        and_ln407_1_reg_2307_pp0_iter8_reg <= and_ln407_1_reg_2307_pp0_iter7_reg;
        and_ln407_1_reg_2307_pp0_iter9_reg <= and_ln407_1_reg_2307_pp0_iter8_reg;
        b_exp_2_reg_2292_pp0_iter2_reg <= b_exp_2_reg_2292_pp0_iter1_reg;
        b_exp_2_reg_2292_pp0_iter3_reg <= b_exp_2_reg_2292_pp0_iter2_reg;
        b_exp_2_reg_2292_pp0_iter4_reg <= b_exp_2_reg_2292_pp0_iter3_reg;
        b_exp_2_reg_2292_pp0_iter5_reg <= b_exp_2_reg_2292_pp0_iter4_reg;
        b_exp_2_reg_2292_pp0_iter6_reg <= b_exp_2_reg_2292_pp0_iter5_reg;
        b_exp_2_reg_2292_pp0_iter7_reg <= b_exp_2_reg_2292_pp0_iter6_reg;
        b_exp_2_reg_2292_pp0_iter8_reg <= b_exp_2_reg_2292_pp0_iter7_reg;
        icmp_ln828_1_reg_2281_pp0_iter10_reg <= icmp_ln828_1_reg_2281_pp0_iter9_reg;
        icmp_ln828_1_reg_2281_pp0_iter11_reg <= icmp_ln828_1_reg_2281_pp0_iter10_reg;
        icmp_ln828_1_reg_2281_pp0_iter12_reg <= icmp_ln828_1_reg_2281_pp0_iter11_reg;
        icmp_ln828_1_reg_2281_pp0_iter13_reg <= icmp_ln828_1_reg_2281_pp0_iter12_reg;
        icmp_ln828_1_reg_2281_pp0_iter14_reg <= icmp_ln828_1_reg_2281_pp0_iter13_reg;
        icmp_ln828_1_reg_2281_pp0_iter15_reg <= icmp_ln828_1_reg_2281_pp0_iter14_reg;
        icmp_ln828_1_reg_2281_pp0_iter16_reg <= icmp_ln828_1_reg_2281_pp0_iter15_reg;
        icmp_ln828_1_reg_2281_pp0_iter2_reg <= icmp_ln828_1_reg_2281_pp0_iter1_reg;
        icmp_ln828_1_reg_2281_pp0_iter3_reg <= icmp_ln828_1_reg_2281_pp0_iter2_reg;
        icmp_ln828_1_reg_2281_pp0_iter4_reg <= icmp_ln828_1_reg_2281_pp0_iter3_reg;
        icmp_ln828_1_reg_2281_pp0_iter5_reg <= icmp_ln828_1_reg_2281_pp0_iter4_reg;
        icmp_ln828_1_reg_2281_pp0_iter6_reg <= icmp_ln828_1_reg_2281_pp0_iter5_reg;
        icmp_ln828_1_reg_2281_pp0_iter7_reg <= icmp_ln828_1_reg_2281_pp0_iter6_reg;
        icmp_ln828_1_reg_2281_pp0_iter8_reg <= icmp_ln828_1_reg_2281_pp0_iter7_reg;
        icmp_ln828_1_reg_2281_pp0_iter9_reg <= icmp_ln828_1_reg_2281_pp0_iter8_reg;
        icmp_ln828_reg_2263_pp0_iter10_reg <= icmp_ln828_reg_2263_pp0_iter9_reg;
        icmp_ln828_reg_2263_pp0_iter11_reg <= icmp_ln828_reg_2263_pp0_iter10_reg;
        icmp_ln828_reg_2263_pp0_iter12_reg <= icmp_ln828_reg_2263_pp0_iter11_reg;
        icmp_ln828_reg_2263_pp0_iter13_reg <= icmp_ln828_reg_2263_pp0_iter12_reg;
        icmp_ln828_reg_2263_pp0_iter14_reg <= icmp_ln828_reg_2263_pp0_iter13_reg;
        icmp_ln828_reg_2263_pp0_iter15_reg <= icmp_ln828_reg_2263_pp0_iter14_reg;
        icmp_ln828_reg_2263_pp0_iter16_reg <= icmp_ln828_reg_2263_pp0_iter15_reg;
        icmp_ln828_reg_2263_pp0_iter2_reg <= icmp_ln828_reg_2263_pp0_iter1_reg;
        icmp_ln828_reg_2263_pp0_iter3_reg <= icmp_ln828_reg_2263_pp0_iter2_reg;
        icmp_ln828_reg_2263_pp0_iter4_reg <= icmp_ln828_reg_2263_pp0_iter3_reg;
        icmp_ln828_reg_2263_pp0_iter5_reg <= icmp_ln828_reg_2263_pp0_iter4_reg;
        icmp_ln828_reg_2263_pp0_iter6_reg <= icmp_ln828_reg_2263_pp0_iter5_reg;
        icmp_ln828_reg_2263_pp0_iter7_reg <= icmp_ln828_reg_2263_pp0_iter6_reg;
        icmp_ln828_reg_2263_pp0_iter8_reg <= icmp_ln828_reg_2263_pp0_iter7_reg;
        icmp_ln828_reg_2263_pp0_iter9_reg <= icmp_ln828_reg_2263_pp0_iter8_reg;
        p_Result_16_reg_2499_pp0_iter10_reg <= p_Result_16_reg_2499;
        r_exp_V_reg_2519_pp0_iter13_reg <= r_exp_V_reg_2519;
        r_exp_V_reg_2519_pp0_iter14_reg <= r_exp_V_reg_2519_pp0_iter13_reg;
        r_exp_V_reg_2519_pp0_iter15_reg <= r_exp_V_reg_2519_pp0_iter14_reg;
        ret_V_17_reg_2494_pp0_iter10_reg <= ret_V_17_reg_2494;
        ret_V_17_reg_2494_pp0_iter11_reg <= ret_V_17_reg_2494_pp0_iter10_reg;
        ret_V_17_reg_2494_pp0_iter12_reg <= ret_V_17_reg_2494_pp0_iter11_reg;
        ret_V_17_reg_2494_pp0_iter13_reg <= ret_V_17_reg_2494_pp0_iter12_reg;
        ret_V_17_reg_2494_pp0_iter14_reg <= ret_V_17_reg_2494_pp0_iter13_reg;
        ret_V_17_reg_2494_pp0_iter15_reg <= ret_V_17_reg_2494_pp0_iter14_reg;
        sel_tmp13_reg_2313_pp0_iter10_reg <= sel_tmp13_reg_2313_pp0_iter9_reg;
        sel_tmp13_reg_2313_pp0_iter11_reg <= sel_tmp13_reg_2313_pp0_iter10_reg;
        sel_tmp13_reg_2313_pp0_iter12_reg <= sel_tmp13_reg_2313_pp0_iter11_reg;
        sel_tmp13_reg_2313_pp0_iter13_reg <= sel_tmp13_reg_2313_pp0_iter12_reg;
        sel_tmp13_reg_2313_pp0_iter14_reg <= sel_tmp13_reg_2313_pp0_iter13_reg;
        sel_tmp13_reg_2313_pp0_iter15_reg <= sel_tmp13_reg_2313_pp0_iter14_reg;
        sel_tmp13_reg_2313_pp0_iter16_reg <= sel_tmp13_reg_2313_pp0_iter15_reg;
        sel_tmp13_reg_2313_pp0_iter2_reg <= sel_tmp13_reg_2313_pp0_iter1_reg;
        sel_tmp13_reg_2313_pp0_iter3_reg <= sel_tmp13_reg_2313_pp0_iter2_reg;
        sel_tmp13_reg_2313_pp0_iter4_reg <= sel_tmp13_reg_2313_pp0_iter3_reg;
        sel_tmp13_reg_2313_pp0_iter5_reg <= sel_tmp13_reg_2313_pp0_iter4_reg;
        sel_tmp13_reg_2313_pp0_iter6_reg <= sel_tmp13_reg_2313_pp0_iter5_reg;
        sel_tmp13_reg_2313_pp0_iter7_reg <= sel_tmp13_reg_2313_pp0_iter6_reg;
        sel_tmp13_reg_2313_pp0_iter8_reg <= sel_tmp13_reg_2313_pp0_iter7_reg;
        sel_tmp13_reg_2313_pp0_iter9_reg <= sel_tmp13_reg_2313_pp0_iter8_reg;
        tmp_2_reg_2404_pp0_iter6_reg <= tmp_2_reg_2404;
        tmp_2_reg_2404_pp0_iter7_reg <= tmp_2_reg_2404_pp0_iter6_reg;
        tmp_7_reg_2421_pp0_iter7_reg <= tmp_7_reg_2421;
        tmp_9_reg_2387_pp0_iter5_reg <= tmp_9_reg_2387;
        tmp_9_reg_2387_pp0_iter6_reg <= tmp_9_reg_2387_pp0_iter5_reg;
        tmp_9_reg_2387_pp0_iter7_reg <= tmp_9_reg_2387_pp0_iter6_reg;
        trunc_ln2_reg_2509_pp0_iter10_reg <= trunc_ln2_reg_2509;
        trunc_ln2_reg_2509_pp0_iter11_reg <= trunc_ln2_reg_2509_pp0_iter10_reg;
        trunc_ln2_reg_2509_pp0_iter12_reg <= trunc_ln2_reg_2509_pp0_iter11_reg;
        x_is_1_reg_2268_pp0_iter10_reg <= x_is_1_reg_2268_pp0_iter9_reg;
        x_is_1_reg_2268_pp0_iter11_reg <= x_is_1_reg_2268_pp0_iter10_reg;
        x_is_1_reg_2268_pp0_iter12_reg <= x_is_1_reg_2268_pp0_iter11_reg;
        x_is_1_reg_2268_pp0_iter13_reg <= x_is_1_reg_2268_pp0_iter12_reg;
        x_is_1_reg_2268_pp0_iter14_reg <= x_is_1_reg_2268_pp0_iter13_reg;
        x_is_1_reg_2268_pp0_iter15_reg <= x_is_1_reg_2268_pp0_iter14_reg;
        x_is_1_reg_2268_pp0_iter16_reg <= x_is_1_reg_2268_pp0_iter15_reg;
        x_is_1_reg_2268_pp0_iter2_reg <= x_is_1_reg_2268_pp0_iter1_reg;
        x_is_1_reg_2268_pp0_iter3_reg <= x_is_1_reg_2268_pp0_iter2_reg;
        x_is_1_reg_2268_pp0_iter4_reg <= x_is_1_reg_2268_pp0_iter3_reg;
        x_is_1_reg_2268_pp0_iter5_reg <= x_is_1_reg_2268_pp0_iter4_reg;
        x_is_1_reg_2268_pp0_iter6_reg <= x_is_1_reg_2268_pp0_iter5_reg;
        x_is_1_reg_2268_pp0_iter7_reg <= x_is_1_reg_2268_pp0_iter6_reg;
        x_is_1_reg_2268_pp0_iter8_reg <= x_is_1_reg_2268_pp0_iter7_reg;
        x_is_1_reg_2268_pp0_iter9_reg <= x_is_1_reg_2268_pp0_iter8_reg;
        x_is_p1_reg_2275_pp0_iter10_reg <= x_is_p1_reg_2275_pp0_iter9_reg;
        x_is_p1_reg_2275_pp0_iter11_reg <= x_is_p1_reg_2275_pp0_iter10_reg;
        x_is_p1_reg_2275_pp0_iter12_reg <= x_is_p1_reg_2275_pp0_iter11_reg;
        x_is_p1_reg_2275_pp0_iter13_reg <= x_is_p1_reg_2275_pp0_iter12_reg;
        x_is_p1_reg_2275_pp0_iter14_reg <= x_is_p1_reg_2275_pp0_iter13_reg;
        x_is_p1_reg_2275_pp0_iter15_reg <= x_is_p1_reg_2275_pp0_iter14_reg;
        x_is_p1_reg_2275_pp0_iter16_reg <= x_is_p1_reg_2275_pp0_iter15_reg;
        x_is_p1_reg_2275_pp0_iter2_reg <= x_is_p1_reg_2275_pp0_iter1_reg;
        x_is_p1_reg_2275_pp0_iter3_reg <= x_is_p1_reg_2275_pp0_iter2_reg;
        x_is_p1_reg_2275_pp0_iter4_reg <= x_is_p1_reg_2275_pp0_iter3_reg;
        x_is_p1_reg_2275_pp0_iter5_reg <= x_is_p1_reg_2275_pp0_iter4_reg;
        x_is_p1_reg_2275_pp0_iter6_reg <= x_is_p1_reg_2275_pp0_iter5_reg;
        x_is_p1_reg_2275_pp0_iter7_reg <= x_is_p1_reg_2275_pp0_iter6_reg;
        x_is_p1_reg_2275_pp0_iter8_reg <= x_is_p1_reg_2275_pp0_iter7_reg;
        x_is_p1_reg_2275_pp0_iter9_reg <= x_is_p1_reg_2275_pp0_iter8_reg;
        zext_ln492_reg_2297_pp0_iter2_reg[5 : 0] <= zext_ln492_reg_2297_pp0_iter1_reg[5 : 0];
        zext_ln492_reg_2297_pp0_iter3_reg[5 : 0] <= zext_ln492_reg_2297_pp0_iter2_reg[5 : 0];
        zext_ln492_reg_2297_pp0_iter4_reg[5 : 0] <= zext_ln492_reg_2297_pp0_iter3_reg[5 : 0];
        zext_ln492_reg_2297_pp0_iter5_reg[5 : 0] <= zext_ln492_reg_2297_pp0_iter4_reg[5 : 0];
        zext_ln492_reg_2297_pp0_iter6_reg[5 : 0] <= zext_ln492_reg_2297_pp0_iter5_reg[5 : 0];
        zext_ln492_reg_2297_pp0_iter7_reg[5 : 0] <= zext_ln492_reg_2297_pp0_iter6_reg[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((sel_tmp13_reg_2313_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (x_is_1_reg_2268_pp0_iter1_reg == 1'd0) & (1'b1 == ap_ce))) begin
        a_1_reg_2348 <= {{ret_V_3_fu_850_p2[75:70]}};
        tmp_4_reg_2354 <= {{ret_V_3_fu_850_p2[69:3]}};
        z2_V_reg_2342 <= {{ret_V_3_fu_850_p2[75:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((sel_tmp13_reg_2313_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (x_is_1_reg_2268_pp0_iter2_reg == 1'd0) & (1'b1 == ap_ce))) begin
        a_2_reg_2365 <= {{ret_V_5_fu_938_p2[81:76]}};
        ret_V_5_reg_2359 <= ret_V_5_fu_938_p2;
        trunc_ln657_3_reg_2371 <= trunc_ln657_3_fu_954_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((sel_tmp13_reg_2313 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (x_is_1_reg_2268 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce))) begin
        a_reg_2326 <= {{mul_ln682_fu_752_p2[53:50]}};
        mul_ln682_reg_2319 <= mul_ln682_fu_752_p2;
        tmp_6_reg_2337 <= mul_ln682_fu_752_p2[32'd53];
        trunc_ln657_reg_2332 <= trunc_ln657_fu_768_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((sel_tmp13_reg_2313_pp0_iter13_reg == 1'd0) & (x_is_1_reg_2268_pp0_iter13_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        add_ln657_7_reg_2568 <= add_ln657_7_fu_1827_p2;
        ret_V_34_reg_2563[25 : 0] <= ret_V_34_fu_1790_p4[25 : 0];
ret_V_34_reg_2563[42 : 35] <= ret_V_34_fu_1790_p4[42 : 35];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce))) begin
        and_ln407_1_reg_2307 <= and_ln407_1_fu_697_p2;
        and_ln407_1_reg_2307_pp0_iter1_reg <= and_ln407_1_reg_2307;
        b_exp_2_reg_2292 <= b_exp_2_fu_660_p3;
        b_exp_2_reg_2292_pp0_iter1_reg <= b_exp_2_reg_2292;
        icmp_ln828_1_reg_2281 <= icmp_ln828_1_fu_630_p2;
        icmp_ln828_1_reg_2281_pp0_iter1_reg <= icmp_ln828_1_reg_2281;
        icmp_ln828_reg_2263 <= icmp_ln828_fu_606_p2;
        icmp_ln828_reg_2263_pp0_iter1_reg <= icmp_ln828_reg_2263;
        p_Repl2_s_reg_2257 <= p_Repl2_s_fu_586_p1;
        p_Result_s_reg_2287 <= p_Val2_s_fu_564_p1[32'd51];
        sel_tmp13_reg_2313 <= sel_tmp13_fu_715_p2;
        sel_tmp13_reg_2313_pp0_iter1_reg <= sel_tmp13_reg_2313;
        x_is_1_reg_2268 <= x_is_1_fu_612_p2;
        x_is_1_reg_2268_pp0_iter1_reg <= x_is_1_reg_2268;
        x_is_p1_reg_2275 <= x_is_p1_fu_624_p2;
        x_is_p1_reg_2275_pp0_iter1_reg <= x_is_p1_reg_2275;
        zext_ln492_reg_2297[5 : 0] <= zext_ln492_fu_668_p1[5 : 0];
        zext_ln492_reg_2297_pp0_iter1_reg[5 : 0] <= zext_ln492_reg_2297[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((sel_tmp13_reg_2313_pp0_iter14_reg == 1'd0) & (x_is_1_reg_2268_pp0_iter14_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        exp_Z1P_m_1_V_reg_2583 <= {{exp_Z1P_m_1_l_V_fu_1921_p2[51:2]}};
        exp_Z1_V_reg_2578 <= pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0;
        exp_Z1_hi_V_reg_2588 <= {{pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0[57:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((sel_tmp13_reg_2313_pp0_iter15_reg == 1'd0) & (x_is_1_reg_2268_pp0_iter15_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        icmp_ln844_reg_2593 <= icmp_ln844_fu_2056_p2;
        icmp_ln848_reg_2598 <= icmp_ln848_fu_2077_p2;
        select_ln657_reg_2603[62 : 0] <= select_ln657_fu_2140_p3[62 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((sel_tmp13_reg_2313_pp0_iter8_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (x_is_1_reg_2268_pp0_iter8_reg == 1'd0) & (1'b1 == ap_ce))) begin
        p_Result_16_reg_2499 <= ret_V_17_fu_1589_p2[32'd119];
        ret_V_17_reg_2494 <= ret_V_17_fu_1589_p2;
        trunc_ln2_reg_2509 <= {{ret_V_17_fu_1589_p2[107:49]}};
    end
end

always @ (posedge ap_clk) begin
    if (((sel_tmp13_reg_2313_pp0_iter11_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (x_is_1_reg_2268_pp0_iter11_reg == 1'd0) & (1'b1 == ap_ce))) begin
        r_exp_V_reg_2519 <= r_exp_V_fu_1677_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((sel_tmp13_reg_2313_pp0_iter6_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (x_is_1_reg_2268_pp0_iter6_reg == 1'd0) & (1'b1 == ap_ce))) begin
        tmp_10_reg_2433 <= {{ret_V_13_fu_1284_p2[124:54]}};
        tmp_11_reg_2438 <= {{ret_V_13_fu_1284_p2[130:125]}};
        z7_V_reg_2427 <= {{ret_V_13_fu_1284_p2[130:54]}};
    end
end

always @ (posedge ap_clk) begin
    if (((sel_tmp13_reg_2313_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (x_is_1_reg_2268_pp0_iter7_reg == 1'd0) & (1'b1 == ap_ce))) begin
        tmp_12_reg_2484 <= {{ret_V_15_fu_1396_p2[135:64]}};
        tmp_13_reg_2489 <= {{ret_V_15_fu_1396_p2[135:96]}};
    end
end

always @ (posedge ap_clk) begin
    if (((sel_tmp13_reg_2313_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (x_is_1_reg_2268_pp0_iter4_reg == 1'd0) & (1'b1 == ap_ce))) begin
        tmp_2_reg_2404 <= {{ret_V_9_fu_1108_p2[120:115]}};
        tmp_s_reg_2399 <= {{ret_V_9_fu_1108_p2[114:34]}};
        z5_V_reg_2393 <= {{ret_V_9_fu_1108_p2[120:34]}};
    end
end

always @ (posedge ap_clk) begin
    if (((sel_tmp13_reg_2313_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (x_is_1_reg_2268_pp0_iter5_reg == 1'd0) & (1'b1 == ap_ce))) begin
        tmp_5_reg_2416 <= {{ret_V_11_fu_1196_p2[119:44]}};
        tmp_7_reg_2421 <= {{ret_V_11_fu_1196_p2[125:120]}};
        z6_V_reg_2410 <= {{ret_V_11_fu_1196_p2[125:44]}};
    end
end

always @ (posedge ap_clk) begin
    if (((sel_tmp13_reg_2313_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (x_is_1_reg_2268_pp0_iter3_reg == 1'd0) & (1'b1 == ap_ce))) begin
        tmp_8_reg_2382 <= {{ret_V_7_fu_1020_p2[95:10]}};
        tmp_9_reg_2387 <= {{ret_V_7_fu_1020_p2[101:96]}};
        z4_V_reg_2376 <= {{ret_V_7_fu_1020_p2[101:10]}};
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1)) | ((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to16 = 1'b1;
    end else begin
        ap_idle_pp0_0to16 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (ap_start == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to16 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce))) begin
        grp_fu_2246_ce = 1'b1;
    end else begin
        grp_fu_2246_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_log0_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_double_0_5_64_array_V_ce0 = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_log0_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_double_0_5_64_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (ap_start == 1'b1))) begin
        pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_V_ce0 = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_12_6_64_array_V_ce0 = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_12_6_64_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_17_6_64_array_V_ce0 = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_17_6_64_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_22_6_64_array_V_ce0 = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_22_6_64_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_27_6_64_array_V_ce0 = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_27_6_64_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_32_6_64_array_V_ce0 = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_32_6_64_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_4_4_16_array_V_ce0 = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_4_4_16_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_7_6_64_array_V_ce0 = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_7_6_64_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce1 = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Elog2_V_fu_1429_p1 = 90'd418981761686000620659953;

assign Z3_fu_1729_p4 = {{m_diff_fu_1704_p2[42:35]}};

assign Z4_fu_1739_p1 = m_diff_fu_1704_p2[34:0];

assign Z4_ind_V_fu_1743_p4 = {{m_diff_fu_1704_p2[34:27]}};

assign add_ln1146_1_fu_2014_p2 = (trunc_ln1146_1_fu_2000_p3 + zext_ln1146_11_fu_1992_p1);

assign add_ln1146_2_fu_2020_p2 = (trunc_ln3_fu_1984_p3 + zext_ln1146_10_fu_1976_p1);

assign add_ln649_fu_1663_p2 = (p_Result_cast_fu_1638_p4 + 13'd1);

assign add_ln657_1_fu_1469_p2 = (zext_ln223_2_fu_1443_p1 + zext_ln223_1_fu_1439_p1);

assign add_ln657_2_fu_1479_p2 = (add_ln657_fu_1463_p2 + zext_ln657_6_fu_1475_p1);

assign add_ln657_3_fu_1485_p2 = (zext_ln223_4_fu_1451_p1 + zext_ln223_3_fu_1447_p1);

assign add_ln657_4_fu_1491_p2 = (zext_ln223_6_fu_1459_p1 + zext_ln223_5_fu_1455_p1);

assign add_ln657_5_fu_1501_p2 = (add_ln657_3_fu_1485_p2 + zext_ln657_7_fu_1497_p1);

assign add_ln657_7_fu_1827_p2 = (zext_ln657_11_fu_1823_p1 + ret_V_33_fu_1784_p2);

assign add_ln657_9_fu_1911_p2 = (zext_ln657_13_fu_1907_p1 + exp_Z2P_m_1_V_fu_1843_p2);

assign add_ln657_fu_1463_p2 = (pow_reduce_anonymous_namespace_log0_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_double_0_5_64_array_V_q0 + zext_ln223_fu_1435_p1);

assign and_ln407_1_fu_697_p2 = (icmp_ln407_fu_679_p2 & and_ln407_fu_691_p2);

assign and_ln407_fu_691_p2 = (xor_ln369_fu_673_p2 & icmp_ln407_1_fu_685_p2);

assign and_ln657_fu_2135_p2 = (icmp_ln844_fu_2056_p2 & and_ln407_1_reg_2307_pp0_iter15_reg);

assign and_ln848_1_fu_2219_p2 = (and_ln848_fu_2214_p2 & and_ln407_1_reg_2307_pp0_iter16_reg);

assign and_ln848_fu_2214_p2 = (xor_ln657_fu_2209_p2 & icmp_ln848_reg_2598);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == ap_ce) | ((ap_start == 1'b0) & (ap_start == 1'b1)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = ((sel_tmp13_reg_2313_pp0_iter16_reg[0:0] === 1'b1) ? select_ln407_3_fu_2195_p3 : select_ln369_fu_2232_p3);

assign b_exp_1_fu_654_p2 = ($signed(zext_ln509_fu_590_p1) + $signed(12'd3074));

assign b_exp_2_fu_660_p3 = ((p_Result_s_fu_636_p3[0:0] === 1'b1) ? b_exp_1_fu_654_p2 : b_exp_fu_594_p2);

assign b_exp_fu_594_p2 = ($signed(zext_ln509_fu_590_p1) + $signed(12'd3073));

assign b_frac_fu_730_p3 = {{1'd1}, {p_Repl2_s_reg_2257}};

assign bitcast_ln520_fu_2131_p1 = p_Result_13_fu_2121_p4;

assign eZ_V_1_fu_965_p4 = {{{{13'd4096}, {ret_V_5_reg_2359}}}, {1'd0}};

assign eZ_V_2_fu_1056_p3 = {{18'd131072}, {z4_V_reg_2376}};

assign eZ_V_3_fu_1144_p3 = {{23'd4194304}, {z5_V_reg_2393}};

assign eZ_V_4_fu_1232_p3 = {{28'd134217728}, {z6_V_reg_2410}};

assign eZ_V_5_fu_1344_p3 = {{33'd4294967296}, {z7_V_reg_2427}};

assign eZ_V_fu_886_p3 = {{8'd128}, {z2_V_reg_2342}};

assign exp_Z1P_m_1_l_V_fu_1921_p2 = (zext_ln1146_8_fu_1893_p1 + zext_ln657_14_fu_1917_p1);

assign exp_Z2P_m_1_V_fu_1843_p2 = (zext_ln1146_7_fu_1837_p1 + zext_ln657_12_fu_1840_p1);

assign exp_Z2_m_1_V_fu_1859_p4 = {{{Z2_reg_2531_pp0_iter14_reg}, {1'd0}}, {tmp_14_fu_1849_p4}};

assign f_Z4_V_fu_1767_p4 = {{pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q1[25:16]}};

assign grp_fu_2246_p1 = 31'd23637;

assign icmp_ln369_fu_600_p2 = ((b_exp_fu_594_p2 == 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln407_1_fu_685_p2 = ((p_Repl2_3_fu_576_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln407_2_fu_703_p2 = ((p_Repl2_3_fu_576_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln407_fu_679_p2 = ((p_Repl2_3_fu_576_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln805_fu_1657_p2 = ((trunc_ln805_fu_1654_p1 == 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln828_1_fu_630_p2 = ((p_Repl2_3_fu_576_p4 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln828_fu_606_p2 = ((p_Repl2_s_fu_586_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln844_fu_2056_p2 = (($signed(tmp_17_fu_2046_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln848_fu_2077_p2 = (($signed(select_ln651_fu_2039_p3) < $signed(13'd7170)) ? 1'b1 : 1'b0);

assign index0_V_fu_644_p4 = {{p_Val2_s_fu_564_p1[51:46]}};

assign lhs_V_11_fu_1239_p3 = {{tmp_5_reg_2416}, {54'd0}};

assign lhs_V_13_fu_1351_p3 = {{tmp_10_reg_2433}, {64'd0}};

assign lhs_V_15_fu_1567_p3 = {{Elog2_V_fu_1429_p2}, {30'd0}};

assign lhs_V_18_fu_1882_p5 = {{{{Z2_reg_2531_pp0_iter14_reg}, {1'd0}}, {tmp_14_fu_1849_p4}}, {2'd0}};

assign lhs_V_1_fu_816_p3 = {{trunc_ln657_reg_2332}, {25'd0}};

assign lhs_V_20_fu_1964_p3 = {{ret_V_23_fu_1947_p2}, {49'd0}};

assign lhs_V_3_fu_893_p3 = {{tmp_4_reg_2354}, {14'd0}};

assign lhs_V_5_fu_974_p3 = {{trunc_ln657_3_reg_2371}, {25'd0}};

assign lhs_V_7_fu_1063_p3 = {{tmp_8_reg_2382}, {34'd0}};

assign lhs_V_9_fu_1151_p3 = {{tmp_s_reg_2399}, {44'd0}};

assign lhs_V_fu_1536_p3 = {{tmp_12_reg_2484}, {45'd0}};

assign log_sum_V_1_fu_1511_p2 = (add_ln657_2_fu_1479_p2 + zext_ln657_8_fu_1507_p1);

assign m_diff_fu_1704_p2 = (trunc_ln2_reg_2509_pp0_iter12_reg - trunc_ln657_1_fu_1694_p4);

assign m_fix_hi_V_fu_1595_p4 = {{ret_V_17_fu_1589_p2[119:104]}};

assign mul_ln682_fu_752_p0 = mul_ln682_fu_752_p00;

assign mul_ln682_fu_752_p00 = pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_V_q0;

assign mul_ln682_fu_752_p1 = ((p_Result_s_reg_2287[0:0] === 1'b1) ? zext_ln1287_1_fu_737_p1 : p_Result_15_fu_721_p4);

assign or_ln407_1_fu_2170_p2 = (x_is_NaN_fu_2153_p2 | x_is_1_reg_2268_pp0_iter16_reg);

assign or_ln407_2_fu_2183_p2 = (x_is_1_reg_2268_pp0_iter16_reg | icmp_ln828_1_reg_2281_pp0_iter16_reg);

assign or_ln407_3_fu_709_p2 = (icmp_ln828_1_fu_630_p2 | icmp_ln407_2_fu_703_p2);

assign or_ln407_fu_2158_p2 = (x_is_p1_reg_2275_pp0_iter16_reg | x_is_NaN_fu_2153_p2);

assign p_Repl2_3_fu_576_p4 = {{p_Val2_s_fu_564_p1[62:52]}};

assign p_Repl2_s_fu_586_p1 = p_Val2_s_fu_564_p1[51:0];

assign p_Result_13_fu_2121_p4 = {{{{1'd0}, {p_Val2_11_fu_2115_p2}}}, {tmp_V_fu_2103_p3}};

assign p_Result_14_fu_568_p3 = p_Val2_s_fu_564_p1[32'd63];

assign p_Result_15_fu_721_p4 = {{{{1'd1}, {p_Repl2_s_reg_2257}}}, {1'd0}};

assign p_Result_7_fu_1647_p3 = grp_fu_2246_p3[32'd30];

assign p_Result_cast_fu_1638_p4 = {{grp_fu_2246_p3[30:18]}};

assign p_Result_s_fu_636_p3 = p_Val2_s_fu_564_p1[32'd51];

assign p_Val2_11_fu_2115_p2 = (trunc_ln170_fu_2111_p1 + 11'd1023);

assign p_Val2_s_fu_564_p1 = base_r;

assign pow_reduce_anonymous_namespace_log0_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_double_0_5_64_array_V_address0 = zext_ln492_reg_2297_pp0_iter7_reg;

assign pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_V_address0 = zext_ln492_fu_668_p1;

assign pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_12_6_64_array_V_address0 = zext_ln492_7_fu_1328_p1;

assign pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_17_6_64_array_V_address0 = zext_ln492_8_fu_1332_p1;

assign pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_22_6_64_array_V_address0 = zext_ln492_9_fu_1336_p1;

assign pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_27_6_64_array_V_address0 = zext_ln492_10_fu_1340_p1;

assign pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_32_6_64_array_V_address0 = zext_ln492_11_fu_1402_p1;

assign pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_4_4_16_array_V_address0 = zext_ln492_1_fu_1320_p1;

assign pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_7_6_64_array_V_address0 = zext_ln492_6_fu_1324_p1;

assign pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 = zext_ln492_2_fu_1763_p1;

assign pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 = zext_ln492_5_fu_1833_p1;

assign pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 = zext_ln492_4_fu_1758_p1;

assign pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address1 = zext_ln492_3_fu_1753_p1;

assign r_V_10_fu_1807_p0 = r_V_10_fu_1807_p00;

assign r_V_10_fu_1807_p00 = ret_V_33_fu_1784_p2;

assign r_V_10_fu_1807_p1 = r_V_10_fu_1807_p10;

assign r_V_10_fu_1807_p10 = ret_V_34_fu_1790_p4;

assign r_V_11_fu_1876_p0 = r_V_11_fu_1876_p00;

assign r_V_11_fu_1876_p00 = exp_Z2P_m_1_V_fu_1843_p2;

assign r_V_11_fu_1876_p1 = r_V_11_fu_1876_p10;

assign r_V_11_fu_1876_p10 = exp_Z2_m_1_V_fu_1859_p4;

assign r_V_13_fu_840_p0 = r_V_13_fu_840_p00;

assign r_V_13_fu_840_p00 = a_reg_2326;

assign r_V_13_fu_840_p1 = r_V_13_fu_840_p10;

assign r_V_13_fu_840_p10 = z1_V_fu_780_p3;

assign r_V_14_fu_1520_p0 = zext_ln1072_12_fu_1517_p1;

assign r_V_14_fu_1520_p1 = zext_ln1072_12_fu_1517_p1;

assign r_V_16_fu_1958_p0 = r_V_16_fu_1958_p00;

assign r_V_16_fu_1958_p00 = exp_Z1P_m_1_V_reg_2583;

assign r_V_16_fu_1958_p1 = r_V_16_fu_1958_p10;

assign r_V_16_fu_1958_p10 = exp_Z1_hi_V_reg_2588;

assign r_V_2_fu_920_p0 = r_V_2_fu_920_p00;

assign r_V_2_fu_920_p00 = a_1_reg_2348;

assign r_V_2_fu_920_p1 = r_V_2_fu_920_p10;

assign r_V_2_fu_920_p10 = z2_V_reg_2342;

assign r_V_3_fu_1002_p0 = r_V_3_fu_1002_p00;

assign r_V_3_fu_1002_p00 = a_2_reg_2365;

assign r_V_3_fu_1002_p1 = r_V_3_fu_1002_p10;

assign r_V_3_fu_1002_p10 = z3_V_fu_958_p3;

assign r_V_4_fu_1090_p0 = r_V_4_fu_1090_p00;

assign r_V_4_fu_1090_p00 = tmp_9_reg_2387;

assign r_V_4_fu_1090_p1 = r_V_4_fu_1090_p10;

assign r_V_4_fu_1090_p10 = z4_V_reg_2376;

assign r_V_5_fu_1178_p0 = r_V_5_fu_1178_p00;

assign r_V_5_fu_1178_p00 = tmp_2_reg_2404;

assign r_V_5_fu_1178_p1 = r_V_5_fu_1178_p10;

assign r_V_5_fu_1178_p10 = z5_V_reg_2393;

assign r_V_6_fu_1266_p0 = r_V_6_fu_1266_p00;

assign r_V_6_fu_1266_p00 = tmp_7_reg_2421;

assign r_V_6_fu_1266_p1 = r_V_6_fu_1266_p10;

assign r_V_6_fu_1266_p10 = z6_V_reg_2410;

assign r_V_7_fu_1378_p0 = r_V_7_fu_1378_p00;

assign r_V_7_fu_1378_p00 = tmp_11_reg_2438;

assign r_V_7_fu_1378_p1 = r_V_7_fu_1378_p10;

assign r_V_7_fu_1378_p10 = z7_V_reg_2427;

assign r_exp_V_1_fu_2034_p2 = ($signed(r_exp_V_reg_2519_pp0_iter15_reg) + $signed(13'd8191));

assign r_exp_V_fu_1677_p3 = ((p_Result_7_fu_1647_p3[0:0] === 1'b1) ? select_ln804_fu_1669_p3 : p_Result_cast_fu_1638_p4);

assign ret_V_11_fu_1196_p2 = (ret_V_29_fu_1166_p2 - zext_ln1147_4_fu_1192_p1);

assign ret_V_13_fu_1284_p2 = (ret_V_30_fu_1254_p2 - zext_ln1147_5_fu_1280_p1);

assign ret_V_15_fu_1396_p2 = (ret_V_31_fu_1366_p2 - zext_ln1147_6_fu_1392_p1);

assign ret_V_16_fu_1579_p2 = ($signed(sext_ln1146_fu_1575_p1) + $signed(lhs_V_15_fu_1567_p3));

assign ret_V_17_fu_1589_p2 = ($signed(sext_ln1146_1_fu_1585_p1) + $signed(ret_V_16_fu_1579_p2));

assign ret_V_23_fu_1947_p2 = (exp_Z1_V_reg_2578 + 58'd16);

assign ret_V_24_fu_2008_p2 = (zext_ln1146_9_fu_1972_p1 + lhs_V_20_fu_1964_p3);

assign ret_V_25_fu_827_p2 = (select_ln1287_fu_809_p3 + zext_ln1146_fu_823_p1);

assign ret_V_26_fu_908_p2 = (zext_ln657_fu_904_p1 + zext_ln1146_1_fu_900_p1);

assign ret_V_27_fu_989_p2 = (zext_ln657_1_fu_985_p1 + zext_ln1146_2_fu_981_p1);

assign ret_V_28_fu_1078_p2 = (zext_ln657_2_fu_1074_p1 + zext_ln1146_3_fu_1070_p1);

assign ret_V_29_fu_1166_p2 = (zext_ln657_3_fu_1162_p1 + zext_ln1146_4_fu_1158_p1);

assign ret_V_30_fu_1254_p2 = (zext_ln657_4_fu_1250_p1 + zext_ln1146_5_fu_1246_p1);

assign ret_V_31_fu_1366_p2 = (zext_ln657_5_fu_1362_p1 + zext_ln1146_6_fu_1358_p1);

assign ret_V_33_fu_1784_p2 = (zext_ln657_10_fu_1780_p1 + zext_ln657_9_fu_1777_p1);

assign ret_V_34_fu_1790_p4 = {{{Z3_reg_2538}, {9'd0}}, {pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0}};

assign ret_V_3_fu_850_p2 = (ret_V_25_fu_827_p2 - zext_ln1147_fu_846_p1);

assign ret_V_5_fu_938_p2 = (ret_V_26_fu_908_p2 - zext_ln1147_1_fu_934_p1);

assign ret_V_7_fu_1020_p2 = (ret_V_27_fu_989_p2 - zext_ln1147_2_fu_1016_p1);

assign ret_V_9_fu_1108_p2 = (ret_V_28_fu_1078_p2 - zext_ln1147_3_fu_1104_p1);

assign ret_V_fu_1551_p2 = (zext_ln1147_7_fu_1543_p1 - zext_ln1147_8_fu_1547_p1);

assign rhs_V_10_fu_1272_p3 = {{r_V_6_fu_1266_p2}, {21'd0}};

assign rhs_V_12_fu_1384_p3 = {{r_V_7_fu_1378_p2}, {26'd0}};

assign rhs_V_13_fu_1627_p3 = {{p_Result_16_reg_2499_pp0_iter10_reg}, {18'd131072}};

assign rhs_V_2_fu_926_p3 = {{r_V_2_fu_920_p2}, {1'd0}};

assign rhs_V_4_fu_1008_p3 = {{r_V_3_fu_1002_p2}, {6'd0}};

assign rhs_V_6_fu_1096_p3 = {{r_V_4_fu_1090_p2}, {11'd0}};

assign rhs_V_8_fu_1184_p3 = {{r_V_5_fu_1178_p2}, {16'd0}};

assign rhs_V_s_fu_1526_p4 = {{r_V_14_fu_1520_p2[79:1]}};

assign sel_tmp13_fu_715_p2 = (xor_ln369_fu_673_p2 & or_ln407_3_fu_709_p2);

assign sel_tmp14_fu_2203_p3 = ((sel_tmp13_reg_2313_pp0_iter16_reg[0:0] === 1'b1) ? select_ln407_3_fu_2195_p3 : select_ln657_reg_2603);

assign select_ln1287_fu_809_p3 = ((tmp_6_reg_2337[0:0] === 1'b1) ? tmp_3_fu_796_p4 : zext_ln1287_fu_805_p1);

assign select_ln369_fu_2232_p3 = ((x_is_1_reg_2268_pp0_iter16_reg[0:0] === 1'b1) ? select_ln407_1_fu_2175_p3 : select_ln848_fu_2224_p3);

assign select_ln407_1_fu_2175_p3 = ((or_ln407_fu_2158_p2[0:0] === 1'b1) ? select_ln407_fu_2163_p3 : 64'd4607182418800017408);

assign select_ln407_2_fu_2187_p3 = ((or_ln407_1_fu_2170_p2[0:0] === 1'b1) ? select_ln407_1_fu_2175_p3 : 64'd9218868437227405312);

assign select_ln407_3_fu_2195_p3 = ((or_ln407_2_fu_2183_p2[0:0] === 1'b1) ? select_ln407_2_fu_2187_p3 : 64'd0);

assign select_ln407_fu_2163_p3 = ((x_is_p1_reg_2275_pp0_iter16_reg[0:0] === 1'b1) ? 64'd4607182418800017408 : 64'd9223372036854775807);

assign select_ln651_fu_2039_p3 = ((tmp_16_fu_2026_p3[0:0] === 1'b1) ? r_exp_V_reg_2519_pp0_iter15_reg : r_exp_V_1_fu_2034_p2);

assign select_ln657_fu_2140_p3 = ((and_ln657_fu_2135_p2[0:0] === 1'b1) ? select_ln658_fu_2069_p3 : bitcast_ln520_fu_2131_p1);

assign select_ln658_fu_2069_p3 = ((tmp_18_fu_2062_p3[0:0] === 1'b1) ? 64'd0 : 64'd9218868437227405312);

assign select_ln804_fu_1669_p3 = ((icmp_ln805_fu_1657_p2[0:0] === 1'b1) ? p_Result_cast_fu_1638_p4 : add_ln649_fu_1663_p2);

assign select_ln848_fu_2224_p3 = ((and_ln848_1_fu_2219_p2[0:0] === 1'b1) ? 64'd0 : sel_tmp14_fu_2203_p3);

assign sext_ln1146_1_fu_1585_p1 = $signed(trunc_ln1_fu_1557_p4);

assign sext_ln1146_fu_1575_p1 = $signed(log_sum_V_1_fu_1511_p2);

assign sf_fu_787_p4 = {{{{5'd16}, {mul_ln682_reg_2319}}}, {16'd0}};

assign tmp_14_fu_1849_p4 = {{pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0[41:2]}};

assign tmp_16_fu_2026_p3 = ret_V_24_fu_2008_p2[32'd106];

assign tmp_17_fu_2046_p4 = {{select_ln651_fu_2039_p3[12:10]}};

assign tmp_18_fu_2062_p3 = ret_V_17_reg_2494_pp0_iter15_reg[32'd119];

assign tmp_1_fu_2093_p4 = {{add_ln1146_1_fu_2014_p2[104:53]}};

assign tmp_3_fu_796_p4 = {{{{5'd16}, {mul_ln682_reg_2319}}}, {17'd0}};

assign tmp_V_fu_2103_p3 = ((tmp_16_fu_2026_p3[0:0] === 1'b1) ? tmp_fu_2083_p4 : tmp_1_fu_2093_p4);

assign tmp_fu_2083_p4 = {{add_ln1146_2_fu_2020_p2[105:54]}};

assign trunc_ln1146_1_fu_2000_p3 = {{trunc_ln1146_2_fu_1996_p1}, {49'd0}};

assign trunc_ln1146_2_fu_1996_p1 = ret_V_23_fu_1947_p2[55:0];

assign trunc_ln1146_fu_1980_p1 = ret_V_23_fu_1947_p2[56:0];

assign trunc_ln170_fu_2111_p1 = select_ln651_fu_2039_p3[10:0];

assign trunc_ln1_fu_1557_p4 = {{ret_V_fu_1551_p2[117:45]}};

assign trunc_ln3_fu_1984_p3 = {{trunc_ln1146_fu_1980_p1}, {49'd0}};

assign trunc_ln657_1_fu_1694_p4 = {{r_V_fu_1688_p2[70:12]}};

assign trunc_ln657_2_fu_1897_p4 = {{r_V_11_fu_1876_p2[92:57]}};

assign trunc_ln657_3_fu_954_p1 = ret_V_5_fu_938_p2[75:0];

assign trunc_ln657_fu_768_p1 = mul_ln682_fu_752_p2[49:0];

assign trunc_ln657_s_fu_1813_p4 = {{r_V_10_fu_1807_p2[78:59]}};

assign trunc_ln805_fu_1654_p1 = grp_fu_2246_p3[17:0];

assign x_is_1_fu_612_p2 = (icmp_ln828_fu_606_p2 & icmp_ln369_fu_600_p2);

assign x_is_NaN_fu_2153_p2 = (xor_ln832_fu_2148_p2 & icmp_ln828_1_reg_2281_pp0_iter16_reg);

assign x_is_p1_fu_624_p2 = (xor_ln964_fu_618_p2 & x_is_1_fu_612_p2);

assign xor_ln369_fu_673_p2 = (x_is_1_fu_612_p2 ^ 1'd1);

assign xor_ln657_fu_2209_p2 = (icmp_ln844_reg_2593 ^ 1'd1);

assign xor_ln832_fu_2148_p2 = (icmp_ln828_reg_2263_pp0_iter16_reg ^ 1'd1);

assign xor_ln964_fu_618_p2 = (p_Result_14_fu_568_p3 ^ 1'd1);

assign z1_V_fu_780_p3 = {{mul_ln682_reg_2319}, {17'd0}};

assign z3_V_fu_958_p3 = {{ret_V_5_reg_2359}, {1'd0}};

assign zext_ln1072_12_fu_1517_p1 = tmp_13_reg_2489;

assign zext_ln1146_10_fu_1976_p1 = r_V_16_fu_1958_p2;

assign zext_ln1146_11_fu_1992_p1 = r_V_16_fu_1958_p2;

assign zext_ln1146_1_fu_900_p1 = lhs_V_3_fu_893_p3;

assign zext_ln1146_2_fu_981_p1 = lhs_V_5_fu_974_p3;

assign zext_ln1146_3_fu_1070_p1 = lhs_V_7_fu_1063_p3;

assign zext_ln1146_4_fu_1158_p1 = lhs_V_9_fu_1151_p3;

assign zext_ln1146_5_fu_1246_p1 = lhs_V_11_fu_1239_p3;

assign zext_ln1146_6_fu_1358_p1 = lhs_V_13_fu_1351_p3;

assign zext_ln1146_7_fu_1837_p1 = ret_V_34_reg_2563;

assign zext_ln1146_8_fu_1893_p1 = lhs_V_18_fu_1882_p5;

assign zext_ln1146_9_fu_1972_p1 = r_V_16_fu_1958_p2;

assign zext_ln1146_fu_823_p1 = lhs_V_1_fu_816_p3;

assign zext_ln1147_1_fu_934_p1 = rhs_V_2_fu_926_p3;

assign zext_ln1147_2_fu_1016_p1 = rhs_V_4_fu_1008_p3;

assign zext_ln1147_3_fu_1104_p1 = rhs_V_6_fu_1096_p3;

assign zext_ln1147_4_fu_1192_p1 = rhs_V_8_fu_1184_p3;

assign zext_ln1147_5_fu_1280_p1 = rhs_V_10_fu_1272_p3;

assign zext_ln1147_6_fu_1392_p1 = rhs_V_12_fu_1384_p3;

assign zext_ln1147_7_fu_1543_p1 = lhs_V_fu_1536_p3;

assign zext_ln1147_8_fu_1547_p1 = rhs_V_s_fu_1526_p4;

assign zext_ln1147_fu_846_p1 = r_V_13_fu_840_p2;

assign zext_ln1287_1_fu_737_p1 = b_frac_fu_730_p3;

assign zext_ln1287_fu_805_p1 = sf_fu_787_p4;

assign zext_ln223_1_fu_1439_p1 = pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_7_6_64_array_V_q0;

assign zext_ln223_2_fu_1443_p1 = pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_12_6_64_array_V_q0;

assign zext_ln223_3_fu_1447_p1 = pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_17_6_64_array_V_q0;

assign zext_ln223_4_fu_1451_p1 = pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_22_6_64_array_V_q0;

assign zext_ln223_5_fu_1455_p1 = pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_27_6_64_array_V_q0;

assign zext_ln223_6_fu_1459_p1 = pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_32_6_64_array_V_q0;

assign zext_ln223_fu_1435_p1 = pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_121_12_ap_q_mode_5_ap_o_mode_3_0_4_4_16_array_V_q0;

assign zext_ln492_10_fu_1340_p1 = tmp_7_reg_2421_pp0_iter7_reg;

assign zext_ln492_11_fu_1402_p1 = tmp_11_reg_2438;

assign zext_ln492_1_fu_1320_p1 = a_reg_2326_pp0_iter7_reg;

assign zext_ln492_2_fu_1763_p1 = m_diff_hi_V_reg_2526;

assign zext_ln492_3_fu_1753_p1 = Z4_ind_V_fu_1743_p4;

assign zext_ln492_4_fu_1758_p1 = Z3_fu_1729_p4;

assign zext_ln492_5_fu_1833_p1 = Z2_reg_2531;

assign zext_ln492_6_fu_1324_p1 = a_1_reg_2348_pp0_iter7_reg;

assign zext_ln492_7_fu_1328_p1 = a_2_reg_2365_pp0_iter7_reg;

assign zext_ln492_8_fu_1332_p1 = tmp_9_reg_2387_pp0_iter7_reg;

assign zext_ln492_9_fu_1336_p1 = tmp_2_reg_2404_pp0_iter7_reg;

assign zext_ln492_fu_668_p1 = index0_V_fu_644_p4;

assign zext_ln509_fu_590_p1 = p_Repl2_3_fu_576_p4;

assign zext_ln657_10_fu_1780_p1 = f_Z4_V_fu_1767_p4;

assign zext_ln657_11_fu_1823_p1 = trunc_ln657_s_fu_1813_p4;

assign zext_ln657_12_fu_1840_p1 = add_ln657_7_reg_2568;

assign zext_ln657_13_fu_1907_p1 = trunc_ln657_2_fu_1897_p4;

assign zext_ln657_14_fu_1917_p1 = add_ln657_9_fu_1911_p2;

assign zext_ln657_1_fu_985_p1 = eZ_V_1_fu_965_p4;

assign zext_ln657_2_fu_1074_p1 = eZ_V_2_fu_1056_p3;

assign zext_ln657_3_fu_1162_p1 = eZ_V_3_fu_1144_p3;

assign zext_ln657_4_fu_1250_p1 = eZ_V_4_fu_1232_p3;

assign zext_ln657_5_fu_1362_p1 = eZ_V_5_fu_1344_p3;

assign zext_ln657_6_fu_1475_p1 = add_ln657_1_fu_1469_p2;

assign zext_ln657_7_fu_1497_p1 = add_ln657_4_fu_1491_p2;

assign zext_ln657_8_fu_1507_p1 = add_ln657_5_fu_1501_p2;

assign zext_ln657_9_fu_1777_p1 = Z4_reg_2543;

assign zext_ln657_fu_904_p1 = eZ_V_fu_886_p3;

always @ (posedge ap_clk) begin
    zext_ln492_reg_2297[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln492_reg_2297_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln492_reg_2297_pp0_iter2_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln492_reg_2297_pp0_iter3_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln492_reg_2297_pp0_iter4_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln492_reg_2297_pp0_iter5_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln492_reg_2297_pp0_iter6_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln492_reg_2297_pp0_iter7_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    ret_V_34_reg_2563[34:26] <= 9'b000000000;
    select_ln657_reg_2603[63] <= 1'b0;
end

endmodule //farthest_point_sampling_pow_generic_double_s
